CMAKE_MINIMUM_REQUIRED (VERSION 3.12...4.0)
PROJECT (dnf-plugins-perfmetrics CXX)

SET (CMAKE_CXX_STANDARD 20)
SET (CMAKE_CXX_STANDARD_REQUIRED ON)
SET (CMAKE_CXX_VISIBILITY_PRESET hidden)

INCLUDE (GNUInstallDirs)

FIND_PACKAGE (PkgConfig REQUIRED)
PKG_CHECK_MODULES (LIBDNF5 REQUIRED libdnf5)
PKG_CHECK_MODULES (JSONC REQUIRED json-c)

SET (SYSCONFDIR ${CMAKE_INSTALL_FULL_SYSCONFDIR})

ADD_SUBDIRECTORY (etc)
ADD_SUBDIRECTORY (plugins)
